### PR TITLE
Adds logic to remove all policies assigned to gh users

### PR DESCRIPTION
**Pull request by riuvshin**
remove all policy mappings from GH user entities in vault so policies can be applied only for teams not gh users

cc @jmelis @maorfr

### CODE REVIEW

**Comment by maorfr** [comment]
[test]

**Comment by riuvshin** [comment]
@maorfr  I've fixed tests

**Comment by maorfr** [comment]
[test]

**Comment by maorfr** [comment]
thanks a lot @riuvshin!
your contributions are always welcome here.

**Pull request merged**
