### PR TITLE
Go version upgrade and /vendor removal

### PR DESCRIPTION
**Pull request by dwelch0**
upgrade from 1.12 to 1.17

Note that `/vendor` is entirely optional when using `go mod`. Removing to conform with more recent app-sre golang projects

### CODE REVIEW

**Comment by rporres** [comment]
Hmm, we're removing `/vendor` of some of our projects, such as `aws-resource-exporter`. Should we make it a practice for all of our own go projects?

cc @jboll @maorfr

**Comment by dwelch0** [comment]
My browser would appreciate its removal for PRs like this :sweat_smile:

**Comment by fishi0x01** [comment]
I actually like the vendor dir strategy a lot :sweat_smile:, mainly because it offers better isolation from 3rd parties -> more deterministic and safe builds. 
Did we agree somewhere on removing it?

**Review by fishi0x01 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
