### PR TITLE
Improve vault manger

### PR DESCRIPTION
**Pull request by riuvshin**
in this PR
- policy mappings now properly reconciled, so it can be deleted from vault if it is removed from app-interface
- nicer, more clean logs
- improve vault client usage, avoid auth for every request to vault to improve performance.

### CODE REVIEW

**Comment by maorfr** [comment]
I ran the code locally and it performed login 52 times.
is this expected?

**Comment by riuvshin** [comment]
@maorfr yes, this PR mostly about fixing policy mappings and logs. there will be another PR related to perf

**Comment by riuvshin** [comment]
@maorfr so I've fixed login many times in this branch. now it should not login many times

**Comment by maorfr** [comment]
lgtm

**Pull request merged**
