### PR TITLE
FROM quay.io instead of docker.io

### PR DESCRIPTION
**Pull request by maorfr**
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/9607

### CODE REVIEW

**Comment by jfchevrette** [comment]
To be consistent with the message we're trying to get across the org, we should move to UBI8 base images. There is a go-toolset and a minimal UBI8 flavours which can be both used in place of the alpine images in this PR

We should also stop mirroring the alpine images as well, assuming they are not being used elsewhere.

@maorfr Let me know if you would like me to propose a change instead of this PR. I'm working on moving all of our Dockerfiles already anyway.

**Comment by maorfr** [comment]
@jfchevrette you are most welcome to take it!
i figured we'd want to split the UBI effort from the docker hub effort, but leaving this for your judgement.
thanks!

**Comment by jfchevrette** [comment]
Resolved in #19

**Pull request closed without merging**
